### ISSUE TITLE
Stream resize error

### ISSUE THREAD

**Issue by ioangatop** [abhiTronix/vidgear#244] opened 2021-09-01 10:12 UTC
Hi! There is an issue with frame fetching from a youtube video when using different resolutions.

Code to reproduce:

```
from vidgear.gears.helper import dimensions_to_resolutions
from vidgear.gears import VideoGear

import pafy
import cv2

source = "https://youtu.be/j1GLs_fMn1s"

video = pafy.new(source) 
valid_streams = dimensions_to_resolutions(
    [stream.resolution for stream in video.allstreams]
)   # ['144p', '240p', '360p', '480p', '720p', '1080p']

options = {
    "STREAM_RESOLUTION": valid_streams[1],  # '240p'
    "STREAM_PARAMS": {"nocheckcertificate": True}
}

stream = VideoGear(
    source=source,
    stream_mode=True,
    **options
).start()

while True:
    frame = stream.read()

    if frame is None:
        break

    cv2.imwrite('frame.jpg', frame)

    break

stream.stop()
```

Fetched image w/ `240p` resolution (happens with  `480p` as well): 
![240](https://user-images.githubusercontent.com/41287808/131653742-e4f6421e-ac1b-462e-8039-cf4fa6fa9e58.jpg)

Fetched image w/ `144p` resolution: 
![144p](https://user-images.githubusercontent.com/41287808/131653679-f5617f51-9c22-4426-9cd4-c19083286330.jpg)

**Logs**
```
10:17:21 :: CamGear :: INFO :: Using Youtube-dl Backend
[ WARN:0] global /opt/opencv-4.5.1/modules/videoio/src/cap_gstreamer.cpp (924) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global /opt/opencv-4.5.1/modules/videoio/src/cap_gstreamer.cpp (961) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=449, duration=-1
10:17:22 :: CamGear :: DEBUG :: Setting backend `1800` for this source.
```

**Comment by abhiTronix** [comment] 2021-09-01 14:37
@ioangatop Yes bug is reproducible. But bug is with OpenCV's GSTREAMER backend and not vidgear. You can test this by:

1. First clone vidgear:

```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear
```

2. Then, commenting this line, so as to disable enforce `cv2.CAP_GSTREAMER` backend. 

https://github.com/abhiTronix/vidgear/blob/eb19b9ce96061c09b5fe4c3ee63d84c940a19af2/vidgear/gears/camgear.py#L136

3. Then install vidgear as:

```sh
  # install normally
  pip install .
```

4. Running your code again with `CAP_FFMPEG` backend:

```python
from vidgear.gears.helper import dimensions_to_resolutions
from vidgear.gears import VideoGear

import pafy
import cv2

source = "https://youtu.be/j1GLs_fMn1s"

video = pafy.new(source)
valid_streams = dimensions_to_resolutions(
    [stream.resolution for stream in video.allstreams]
)  # ['144p', '240p', '360p', '480p', '720p', '1080p']

options = {
    "STREAM_RESOLUTION": valid_streams[1],  # '240p'
    "STREAM_PARAMS": {"nocheckcertificate": True},
}

stream = VideoGear(
    source=source, stream_mode=True, backend="CAP_FFMPEG", **options
).start()

while True:
    frame = stream.read()

    if frame is None:
        break

    cv2.imwrite("frame.jpg", frame)

    break

stream.stop()
```

**Comment by abhiTronix** [comment] 2021-09-01 14:40
@ioangatop Can you confirm your OpenCV version by excuting this command:

```sh
python3 -c "import cv2; print(cv2.__version__)"
```

**Comment by ioangatop** [comment] 2021-09-01 14:43
@abhiTronix thanks for the quick response. My OpenCV version is `4.5.1`.

**Comment by abhiTronix** [comment] 2021-09-01 14:46
> @abhiTronix thanks for the quick response. My OpenCV version is 4.5.1.

@ioangatop Thanks, I'm looking into OpenCV issues for clue.

> I guess there isn't an easier way to change / choose the backend, right?

I can make that simpler, but there's a [bug with FFmpeg](https://github.com/abhiTronix/vidgear/issues/133#issuecomment-638263225), which made me to enforce Gstreamer backend in the first place.

**Comment by abhiTronix** [comment] 2021-09-01 14:52
@ioangatop OpenCV is crappy in doing VideoIO even with backends. I'm thinking to switch FFmpeg decoding completely with issue #148. But unfortunately, It will going to happen next year due to busy 2021. 

I think the best resolution to this problem for now is to  use `360p` or `720p` and then reduce size manually. You can use [`reducer()`](https://abhitronix.github.io/vidgear/v0.2.2-dev/bonus/reference/helper/#vidgear.gears.helper.reducer--reducer) for that purpose.

**Comment by abhiTronix** [comment] 2021-09-01 14:57
I'm closing this issue for now. I'll look into it in later versions.

**Comment by ioangatop** [comment] 2021-09-01 14:58
@abhiTronix thanks! I believe that `worse` and `best` in general don't have a problem, but it's good to have an option to fetch frames with a specific resolution, as it is a nice trade-off of speed and quality.

I'm not sure but I hope that in general, only these resolutions have problems, and its not for this specific stream (meaning if I put another stream `url`, `480p` will act properly but not the `720p`)

**Comment by abhiTronix** [comment] 2021-09-01 15:01
@ioangatop I'm thinking this is to do with GStreamer https://github.com/opencv/opencv/issues/19025#issuecomment-740183729. As we can see errors in logs:
```sh
[ WARN:0] global /home/abhishek/Downloads/opencv-master/modules/videoio/src/cap_gstreamer.cpp (898) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global /home/abhishek/Downloads/opencv-master/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=450, duration=-1

```

**Comment by abhiTronix** [comment] 2021-09-01 15:04
>  and its not for this specific stream (meaning if I put another stream url, 480p will act properly but not the 720p)

@ioangatop This errors is only for Youtube livestreams and not general videos. General videos will works out of the box for any resolution.

**Comment by abhiTronix** [comment] 2021-12-04 03:14
@ioangatop I think #274 will resolve this issue too, can you check it as follows:

Clone and Install `development` branch:

```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout development

  # install normally
  pip install .[core]

  # OR install with asyncio support
  pip install .[asyncio]
```
Test your code:
```python
from vidgear.gears.helper import dimensions_to_resolutions
from vidgear.gears import VideoGear

import pafy
import cv2

source = "https://youtu.be/j1GLs_fMn1s"

options = {
    "STREAM_RESOLUTION": "240p",
    "STREAM_PARAMS": {"nocheckcertificate": True},
}

stream = VideoGear(
    source=source, stream_mode=True, logging=True, **options
).start()

while True:
    frame = stream.read()

    if frame is None:
        break

    cv2.imwrite("frame.jpg", frame)

    break

stream.stop()
```

**Comment by abhiTronix** [comment] 2021-12-04 06:35
**Successfully resolved and merged in commit: https://github.com/abhiTronix/vidgear/commit/dc26c00bcb4ec6e40645b4ad1aa1aedf4f0c6b43**

### Usage docs are available at: https://abhitronix.github.io/vidgear/v0.2.4-dev/gears/camgear/usage/#using-camgear-with-streaming-websites

**Closed by abhiTronix** 2021-12-04 06:35 UTC
Labels: BUG 🐛, EXTERNAL BUG :space_invader:, WORK IN PROGRESS :construction:
