### ISSUE TITLE
[Bug]: In NetGear client.recv() stucking in a some non returnable loop 

### ISSUE THREAD

**Issue by sourabmaity** [abhiTronix/vidgear#374] opened 2023-08-31 14:55 UTC
### Description

I create a simple python code for client and server 

client side in a continuous while loop where its receiving image using client.recv()

server side also in a continuous loop where its sends images to netgear specific address and port 

But I face a problem where client side client.recv() function stuck in some loop I think its not returning any thing when server face some unsurten network issue and disconnected .

How to solve this ?

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

its  has a request_timeout of 5 sec , so its must return None after 5 sec.

### Actual behaviour

Not executing next line of code after client.recv() seems its stuck in a continuous loop 

### Steps to reproduce

1> I found this bug by disconnecting the server in the middle of run. 
2> or disconnecting internet in the middle of run 

### VidGear Version

0.3.1

### Python version

3.11.4

### OpenCV version

4.8.0

### Operating System version

windows10

**Comment by abhiTronix** [comment] 2023-09-02 06:16
@sourabmaity Which `pattern` are you using?

**Comment by abhiTronix** [comment] 2023-09-02 06:32
**Possible duplicate of #361**

**Comment by abhiTronix** [comment] 2023-09-06 19:09
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/3c0dd5d482e5eba37b41a5a2422f65f856e0f27c**

**Closed by abhiTronix** 2023-09-06 19:09 UTC
Labels: BUG :bug:, WORK IN PROGRESS :construction:
