### ISSUE TITLE
[Question]: CamGear stuck when reading local video

### ISSUE THREAD

**Issue by ChuanchuanZheng** [abhiTronix/vidgear#331] opened 2022-08-18 08:23 UTC
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

stream = CamGear(source=test_video_path).start()
    cnt = 0
    while True:
        frame = stream.read()
        if frame is None:
            break
        cnt += 1
        print("reading ===", cnt)
    stream.stop()

Above code runs normal. But when I comment the print line, the code just stuck when finishing reading all the frames. Strange

### VidGear Version

0.2.6

### Python version

3.8.3

### Operating System version

Ubuntu 18.04.6 LTS

**Comment by abhiTronix** [comment] 2022-08-18 10:44
> stream = CamGear(source=test_video_path).start()
cnt = 0
while True:
frame = stream.read()
if frame is None:
break
cnt += 1
print("reading ===", cnt)
stream.stop()

@ChuanchuanZheng This code makes no sense. Provide the proper code.


> Above code runs normal. But when I comment the print line, the code just stuck when finishing reading all the frames. Strange

This also makes no sense as CamGear will stuck on of its own unless if you modify the code and not calling `stop()` after successive calls. Provide terminal logs with `logging=True`, so I will be able to say something.

Kindly provide these information or your issue will be closed.

**Comment by ChuanchuanZheng** [comment] 2022-08-18 10:47
```
stream = CamGear(source=test_video_path).start()
cnt = 0
while True:
    frame = stream.read()
    if frame is None:
        break
    cnt += 1
    # process frame
    print("reading ===", cnt)
stream.stop()
```

**Comment by abhiTronix** [comment] 2022-08-18 11:36
> stream = CamGear(source=test_video_path).start()

What is `test_video_path`?

> stream = CamGear(source=test_video_path).start()
> cnt = 0
> while True:
>     frame = stream.read()
>     if frame is None:
>         break
>     cnt += 1
>     # process frame
>     print("reading ===", cnt)
> stream.stop()

Also I can't reproduce it. It works absolutely fine with or without `print`.

> 19:15:28 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.6
> 19:15:28 ::    CamGear    ::  DEBUG   :: Enabling Threaded Queue Mode for the current video source!

I said "Provide terminal logs with `logging=True`" you haven't enabled `logging`

**Comment by abhiTronix** [comment] 2022-08-18 17:58
### Bug

@ChuanchuanZheng Thanks, Indeed it was a deadlock bug due to [`return self.__queue.get(timeout=self.__thread_timeout)`](https://github.com/abhiTronix/vidgear/blob/6e4eaf6e8f29f4145afabf96d3fc30c8b81f69fc/vidgear/gears/camgear.py#L516) which still waiting for timeout(`thread_timeout`) to happen when queue was empty and main [`update` thread](https://github.com/abhiTronix/vidgear/blob/6e4eaf6e8f29f4145afabf96d3fc30c8b81f69fc/vidgear/gears/camgear.py#L438-L499) was already 
 terminated. Since there was no way to signal queue that stream is already ended, the waiting keep happen untill timeout occurs.

### Solution
The solution was to signal  queue that stream is already ended by putting `None` on exiting the main `update` thread. I'll push commit shortly.

**Comment by abhiTronix** [comment] 2022-08-18 18:09
@ChuanchuanZheng This bug is fixed in commit https://github.com/abhiTronix/vidgear/commit/f06585dfcfacc6ced95e77921e9dfa6e8cf162d6. Kindly test it , you can test this fix by installing `testing` branch as follows:

```python
 # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testingbranch
  git checkout testing

  # install normally
  pip install .[core]

  # OR install with asyncio support
  pip install .[asyncio]
```

After installing, run your test example again. Kindly test it as soon as possible and share your results here. Goodluck!

**Comment by abhiTronix** [comment] 2022-08-19 14:30
Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/f06585dfcfacc6ced95e77921e9dfa6e8cf162d6.

**Comment by abhiTronix** [comment] 2022-08-19 14:30
@ChuanchuanZheng Closed and marked solved for now. Kindly share your results when you're ready. Good luck!

**Closed by abhiTronix** 2022-08-19 14:30 UTC
Labels: BUG :bug:, WAITING TO TEST :timer_clock:, SOLVED :checkered_flag:, WAITING FOR RESPONSE :hourglass_flowing_sand:
