### ISSUE TITLE
[Bug]: NetGear graceful close doesn't work for pattern=2

### ISSUE THREAD

**Issue by brysd** [abhiTronix/vidgear#361] opened 2023-06-13 17:32 UTC
### Description

Hi, it seems that the underlying threads for the NetGear gears never join when an attempt is done to gracefully close the NetGear. This is for pub/sub pattern.

Example (with FastAPI) provided.

```python
from fastapi import FastAPI
from vidgear.gears import NetGear
import threading

app = FastAPI()

gears = []


@app.get("/")
async def root():
    return {"message": "Hello World"}


@app.get("/hello/{name}")
async def say_hello(name: str):
    return {"message": f"Hello {name}"}


@app.on_event("startup")
async def startup():

    gear = NetGear(
        address="*",
        port="5555",
        protocol="tcp",
        pattern=2,
        receive_mode=True,
        logging=True
    )
    gears.append(gear)


@app.on_event("shutdown")
async def shutdown():

    for t in threading.enumerate():
        if t.is_alive() and t != threading.current_thread():
            print(f"background thread {t.name}:{t.ident} is still running")

    for gear in gears:
        gear.close()

```

This results in the following log trace:

```console
INFO:     Uvicorn running on http://0.0.0.0:8003 (Press CTRL+C to quit)
INFO:     Started reloader process [21484] using WatchFiles
INFO:     Started server process [32944]
INFO:     Waiting for application startup.
18:54:33 ::    Helper     ::   INFO   :: Running VidGear Version: 0.3.0
18:54:33 ::    NetGear    ::  DEBUG   :: Threaded Queue Mode is enabled by default for this connection.
18:54:33 ::    NetGear    ::  DEBUG   :: Successfully Binded to address: tcp://*:5558 with pattern: 2.
18:54:33 ::    NetGear    ::  DEBUG   :: JPEG Frame-Compression is activated for this connection with Colorspace:`BGR`, Quality:`90`%, Fastdct:`enabled`, and Fastupsample:`disabled`.
18:54:33 ::    NetGear    ::  DEBUG   :: Multi-threaded Receive Mode is successfully enabled.
18:54:33 ::    NetGear    ::  DEBUG   :: Unique System ID is 48DS1MMQ.
18:54:33 ::    NetGear    ::  DEBUG   :: Receive Mode is now activated.
INFO:     Application startup complete.
INFO:     Shutting down
background thread NetGear:19236 is still running
INFO:     Waiting for application shutdown.
18:54:42 ::    NetGear    ::  DEBUG   :: Terminating various Receive Mode Processes.

```

It seems that the 'graceful' close function never gets passed this "Terminating various Receive Mode Processes" step.
Could it be because the close function tries to join the background threads but eternally waits for them to finish?

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

I would expect that the close function continues to terminate the threads and sockets.

### Actual behaviour

The termination never happens completely. 

We need to kill the python process to stop the application.

### Steps to reproduce

```python
from fastapi import FastAPI
from vidgear.gears import NetGear
import threading

app = FastAPI()

gears = []


@app.get("/")
async def root():
    return {"message": "Hello World"}


@app.get("/hello/{name}")
async def say_hello(name: str):
    return {"message": f"Hello {name}"}


@app.on_event("startup")
async def startup():

    gear = NetGear(
        address="*",
        port="5555",
        protocol="tcp",
        pattern=2,
        receive_mode=True,
        logging=True
    )
    gears.append(gear)


@app.on_event("shutdown")
async def shutdown():

    for t in threading.enumerate():
        if t.is_alive() and t != threading.current_thread():
            print(f"background thread {t.name}:{t.ident} is still running")

    for gear in gears:
        gear.close()

```

### Terminal log output

```shell
INFO:     Uvicorn running on http://0.0.0.0:8003 (Press CTRL+C to quit)
INFO:     Started reloader process [21484] using WatchFiles
INFO:     Started server process [32944]
INFO:     Waiting for application startup.
18:54:33 ::    Helper     ::   INFO   :: Running VidGear Version: 0.3.0
18:54:33 ::    NetGear    ::  DEBUG   :: Threaded Queue Mode is enabled by default for this connection.
18:54:33 ::    NetGear    ::  DEBUG   :: Successfully Binded to address: tcp://*:5558 with pattern: 2.
18:54:33 ::    NetGear    ::  DEBUG   :: JPEG Frame-Compression is activated for this connection with Colorspace:`BGR`, Quality:`90`%, Fastdct:`enabled`, and Fastupsample:`disabled`.
18:54:33 ::    NetGear    ::  DEBUG   :: Multi-threaded Receive Mode is successfully enabled.
18:54:33 ::    NetGear    ::  DEBUG   :: Unique System ID is 48DS1MMQ.
18:54:33 ::    NetGear    ::  DEBUG   :: Receive Mode is now activated.
INFO:     Application startup complete.
INFO:     Shutting down
background thread NetGear:19236 is still running
INFO:     Waiting for application shutdown.
18:54:42 ::    NetGear    ::  DEBUG   :: Terminating various Receive Mode Processes.
```

### Python Code(Optional)

```python
from fastapi import FastAPI
from vidgear.gears import NetGear
import threading

app = FastAPI()

gears = []


@app.get("/")
async def root():
    return {"message": "Hello World"}


@app.get("/hello/{name}")
async def say_hello(name: str):
    return {"message": f"Hello {name}"}


@app.on_event("startup")
async def startup():

    gear = NetGear(
        address="*",
        port="5555",
        protocol="tcp",
        pattern=2,
        receive_mode=True,
        logging=True
    )
    gears.append(gear)


@app.on_event("shutdown")
async def shutdown():

    for t in threading.enumerate():
        if t.is_alive() and t != threading.current_thread():
            print(f"background thread {t.name}:{t.ident} is still running")

    for gear in gears:
        gear.close()
```

### VidGear Version

0.3.0

### Python version

3.8

### OpenCV version

4.7.0.72

### Operating System version

Windows

### Any other Relevant Information?

Also tested on python 3.6, jetpack 4.6.1 (Jetson) and vidgear 2.4.0

**Comment by abhiTronix** [comment] 2023-07-08 21:20
@brysd This is not a bug in vidgear but how ZMQ works. You need the server running to exit the client properly, since `recv_json()` is a blocking function which expects the connection to be made at some point of time. However I can add a flag that kill this process on `close()` forecfully.

**Comment by abhiTronix** [comment] 2023-09-06 19:10
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/3c0dd5d482e5eba37b41a5a2422f65f856e0f27c**

**Closed by abhiTronix** 2023-09-06 19:10 UTC
Labels: ENHANCEMENT :zap:, QUESTION :question:, WORK IN PROGRESS :construction:

**Comment by abhiTronix** [comment] 2023-09-15 08:54
> @abhiTronix You added kill for the NetGear.close, but should not kill added for the CamGear.close() too? On Ctrl + C the process hangs forever in the background.

@AIGeneratedUsername I don't think server side is ever frozen and this problem only exist on receiver end, even you code is using receiver mode(`receive_mode=True`). Secondly, CamGear do provide [`THREAD_TIMEOUT`](https://abhitronix.github.io/vidgear/latest/gears/camgear/advanced/source_params/#exclusive-camgear-attributes) to kill thread on a timeout. Thirdly,  kill for the NetGear.close is not the solution I provided, It is only the last resort when nothing is woking. You need to instead use `subscriber_timeout` optional flag in NetGear API to gracefully timeout if no server is able to connect.

For refrence:

`subscriber_timeout`(integer): Similar to request_timeout, this internal attribute also controls the timeout value (in seconds) but for non-synchronous zmq.PUB/zmq.SUB pattern in compression mode, after which the Client(Subscriber) exit itself with Nonetype value if it's unable to get any response from the socket. It's value can anything greater than 0, and its disabled by default (meaning the client will wait forever for response).
