### ISSUE TITLE
[Bug]: ScreenGear's options wrong names

### ISSUE THREAD

**Issue by xiety** [abhiTronix/vidgear#372] opened 2023-08-23 22:01 UTC
### Description

I need to capture an exact rectangle starting from `x`, `y` and with size of `width` and `height`

I've came up with following working code, but it looks strange:

    options = {"top": x, "left": y, "width": x + width, "height": y + height}

Why `top` should be `x` and not `y`?
Why `width` must be calculated like it is `right`?

I think it should be

    options = {"left": x, "top": y, "width": width, "height": height}

or

    options = {"left": x, "top": y, "right": x + width, "bottom": y + height}

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

Correct bounding box

    (left, top, left+width, top+height)

### Actual behaviour

Incorrect bounding box

    (top, left, width, height)

### Steps to reproduce

irrelevant

### Python Code(Optional)

```python
from vidgear.gears import ScreenGear
    options = {"top": x, "left": y, "width": x + width, "height": y + height}
    stream = ScreenGear(**options).start()
    frame = stream.read()
```

### VidGear Version

0.3.1

### Python version

3.10.7

### OpenCV version

4.8.0

### Operating System version

Windows 10

**Comment by abhiTronix** [comment] 2023-08-26 05:04
@xiety This is not a bug. VidGear follows pillow's [Coordinate System](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#coordinate-system) which states as follows: 

> The Python Imaging Library uses a Cartesian pixel coordinate system, with (0,0) in the upper left corner. Note that the coordinates refer to the implied pixel corners; the centre of a pixel addressed as (0, 0) actually lies at (0.5, 0.5).

> Coordinates are usually passed to the library as 2-tuples (x, y). Rectangles are represented as 4-tuples, (x1, y1, x2, y2), with the upper left corner given first.

That would look like this:

![image](https://github.com/abhiTronix/vidgear/assets/34266896/3c62d2b6-371e-4fb1-a79f-f3183685d892)


Pillow's XY coordinate system, which is different from what you're targeting for. Kindly make changes according to it.

**Comment by xiety** [comment] 2023-08-26 06:08
@abhiTronix, I'm sorry, but I can't understand why I need to put `x` coordinate into the `top` property and not into the `left`

**Comment by abhiTronix** [comment] 2023-08-26 06:32
![image](https://github.com/abhiTronix/vidgear/assets/34266896/06c7fe68-e0a2-4fcc-9e53-dad50412cc35)
Hope this image helps you.

**Comment by abhiTronix** [comment] 2023-08-26 06:33
I never said it should `x` or `y`, it is distance from top.

**Comment by xiety** [comment] 2023-08-26 06:38
But the fact of the matter is that now in the `top` property you need to put the distance from the **left** edge of the screen.

**Comment by xiety** [comment] 2023-08-26 06:56
![diagram copy2](https://github.com/abhiTronix/vidgear/assets/867537/1e38826a-c289-4455-82e6-e29d91efbf0e)

This is how it is working now, which is kinda strange

**Comment by abhiTronix** [comment] 2023-08-26 07:36
@xiety let me check.

**Comment by abhiTronix** [comment] 2023-08-28 17:17
@xiety Yes `"top"` and `"left"` were swapped atleast for `dxcam` backend. But your diagram is incorrect, height and is not from the initial but from the `top+height` and `left+width` respectively, you can confirm this by setting top and left zero and then increasing both the values simultaneously and you could see bounding   moving diagonally.

**Comment by xiety** [comment] 2023-08-28 17:44
I'm doing a simple test:

    from vidgear.gears import ScreenGear
    capture_options = {"top": 100, "left": 100, "width": 700, "height": 700}
    screen = ScreenGear(**capture_options).start()
    image = screen.read()
    print(image.shape)

The result is `(600, 600, 3)` instead of `(700, 700, 3)`. The same with `mss` backend.

**Comment by abhiTronix** [comment] 2023-08-28 18:13
@xiety Apologies, visually this is really hard to see. Yeah you're correct, since all those backend libraries are following [PIL.ImageGrab.grab](https://pillow.readthedocs.io/en/stable/reference/ImageGrab.html) bbox left,upper,right,lower conventions  as explained in depth here: http://chayanvinayak.blogspot.com/2013/03/bounding-box-in-pilpython-image-library.html

**Comment by abhiTronix** [comment] 2023-08-28 18:14
@xiety I'll add this to ScreenGear documentation.

**Comment by abhiTronix** [comment] 2023-09-06 19:10
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/3c0dd5d482e5eba37b41a5a2422f65f856e0f27c**

**Closed by abhiTronix** 2023-09-06 19:10 UTC
Labels: BUG :bug:, WORK IN PROGRESS :construction:
