### ISSUE TITLE
How to record color video?

### ISSUE THREAD

**Issue by Seraphli** [abhiTronix/vidgear#51] opened 2019-09-08 01:52 UTC
## Question

I try the example in the document. The gray image can be recorded. The output video is fine.
But when I comment the color convert code, the video seems corrupt.

```
# import libraries
from vidgear.gears import ScreenGear
from vidgear.gears import WriteGear
import cv2


options = {'top': 40, 'left': 0, 'width': 100, 'height': 100} # define dimensions of screen w.r.t to given monitor to be captured

output_params = {"-vcodec":"libx264", "-crf": 0, "-preset": "fast"} #define (Codec,CRF,preset) FFmpeg tweak parameters for writer


stream = ScreenGear(monitor=1, logging=True, **options).start() #Open Live Screencast on current monitor 

writer = WriteGear(output_filename = 'Output.mp4', compression_mode = True, logging = True, **output_params) #Define writer with output filename 'Output.mp4' 

# infinite loop
while True:
	
	frame = stream.read()
	# read frames

	# check if frame is None
	if frame is None:
		#if True break the infinite loop
		break
	

	# {do something with frame here}
        # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

	# write a modified frame to writer
        writer.write(frame) 
       
        # Show output window
	cv2.imshow("Output Frame", frame)

	key = cv2.waitKey(1) & 0xFF
	# check for 'q' key-press
	if key == ord("q"):
		#if 'q' key-pressed break out
		break

cv2.destroyAllWindows()
# close output window

stream.stop()
# safely close video stream
writer.close()
# safely close writer
```

**Comment by abhiTronix** [comment] 2019-09-08 03:18
@Seraphli **Can you post the terminal log after running this algorithm here? Also, Are you getting corrupt video output each time you run this algorithm, consistently? If possible, Kindly share corrupted video output here too.** Thank you.

**Comment by Seraphli** [comment] 2019-09-08 03:27
The code I used. The image displayed on the opencv window is fine. But the video is corrupt every time. Here is the video. When I unset options for ScreenGear, i.e. recording the whole screen, the problem seems more obvious.
```
# import libraries
from vidgear.gears import ScreenGear
from vidgear.gears import WriteGear
import cv2


options = {'top': 50, 'left': 50, 'width': 200, 'height': 200} # define dimensions of screen w.r.t to given monitor to be captured


output_params = {"-vcodec": "libx264", "-crf": 0,
                 "-preset": "fast"}  # define (Codec,CRF,preset) FFmpeg tweak parameters for writer

stream = ScreenGear(monitor=1,
                    logging=True, **options).start()  # Open Live Screencast on current monitor

writer = WriteGear(output_filename='Output.mp4', compression_mode=True,
                   logging=True,
                   **output_params)  # Define writer with output filename 'Output.mp4'

# infinite loop
while True:

    frame = stream.read()
    # read frames

    # check if frame is None
    if frame is None:
        # if True break the infinite loop
        break

    # {do something with frame here}

    # write a modified frame to writer
    writer.write(frame)

    # Show output window
    cv2.imshow("Output Frame", frame)

    key = cv2.waitKey(1) & 0xFF
    # check for 'q' key-press
    if key == ord("q"):
        # if 'q' key-pressed break out
        break

cv2.destroyAllWindows()
# close output window

stream.stop()
# safely close video stream
writer.close()
# safely close writer
```

**Comment by abhiTronix** [comment] 2019-09-08 03:28
@Seraphli I also need log from your terminal to debug what is causing this behaviour. Thank you.

**Comment by Seraphli** [comment] 2019-09-08 03:31
Here is the log. Thank you.
```
E:\NewDevelop\Seraphli\PythonEnv\kivy\Scripts\python.exe E:/NewDevelop/Seraphli/Github/DesktopTimeLapse/d1.py
Enabling Threaded Queue Mode!
Compression Mode is enabled therefore checking for valid FFmpeg executables!
{'-vcodec': 'libx264', '-crf': '0', '-preset': 'fast'}
FFmpeg Windows Download Path: C:\Users\SErAphLi\AppData\Local\Temp
Final FFmpeg Path: C:\Users\SErAphLi\AppData\Local\Temp\ffmpeg-latest-win64-static/bin/ffmpeg.exe
FFmpeg validity Test Passed!
Found valid FFmpeg Version: `b'N-94664-g0821bc4eee'` installed on this system
Found valid FFmpeg executables: `C:\Users\SErAphLi\AppData\Local\Temp\ffmpeg-latest-win64-static/bin/ffmpeg.exe`
Compression Mode is configured properly!
InputFrame => Height:200 Width:200 Channels:4
C:\Users\SErAphLi\AppData\Local\Temp\ffmpeg-latest-win64-static/bin/ffmpeg.exe -y -f rawvideo -vcodec rawvideo -s 200x200 -pix_fmt bgra -i - -vcodec libx264 -crf 0 -preset fast E:\NewDevelop\Seraphli\Github\DesktopTimeLapse\Output.mp4
ffmpeg version N-94664-g0821bc4eee Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 33.100 / 56. 33.100
  libavcodec     58. 55.101 / 58. 55.101
  libavformat    58. 31.104 / 58. 31.104
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.101 /  7. 58.101
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 32000 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 200x200, 32000 kb/s, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 000000da6e216d40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 000000da6e216d40] profile High 4:4:4 Predictive, level 1.2, 4:4:4, 8-bit
[libx264 @ 000000da6e216d40] 264 - core 158 r2984 3759fcb - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=0 mixed_ref=1 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to 'E:\NewDevelop\Seraphli\Github\DesktopTimeLapse\Output.mp4':
  Metadata:
    encoder         : Lavf58.31.104
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv444p, 200x200, q=-1--1, 25 fps, 12800 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.55.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: 18446744073709551615
frame=  390 fps= 54 q=-1.0 Lsize=     414kB time=00:00:15.56 bitrate= 218.1kbits/s speed=2.14x    
video:412kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.564708%
[libx264 @ 000000da6e216d40] frame I:2     Avg QP: 0.00  size: 12428
[libx264 @ 000000da6e216d40] frame P:388   Avg QP: 0.00  size:  1022
[libx264 @ 000000da6e216d40] mb I  I16..4: 52.7%  0.0% 47.3%
[libx264 @ 000000da6e216d40] mb P  I16..4:  1.7%  0.1%  1.8%  P16..4:  0.8%  0.4%  0.2%  0.0%  0.0%    skip:95.0%
[libx264 @ 000000da6e216d40] 8x8 transform intra:1.7% inter:57.8%
[libx264 @ 000000da6e216d40] coded y,u,v intra: 48.8% 47.5% 47.2% inter: 1.0% 0.9% 0.9%
[libx264 @ 000000da6e216d40] i16 v,h,dc,p: 31% 68%  1%  0%
[libx264 @ 000000da6e216d40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 58% 36%  5%  1%  0%  0%  0%  0%  1%
[libx264 @ 000000da6e216d40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41% 46%  6%  1%  2%  1%  1%  1%  2%
[libx264 @ 000000da6e216d40] Weighted P-Frames: Y:2.8% UV:2.8%
[libx264 @ 000000da6e216d40] ref P L0: 78.8% 21.2%
[libx264 @ 000000da6e216d40] kb/s:216.04

Process finished with exit code 0
```

**Comment by abhiTronix** [comment] 2019-09-08 03:41
@Seraphli Thank you. **Lol, I just watched the video and everything it is working fine. It is matter of understanding how this code is working. As you can see in the video you shared, it is recording a portion/area (defined by dict options = {'top': 50, 'left': 50, 'width': 200, 'height': 200} ) of your computer screen where the opencv's output window is being displayed. To convince you that everything is working fine, kindly remove this `options` flag as in the code as follows:**

```python
# import libraries
from vidgear.gears import ScreenGear
from vidgear.gears import WriteGear
import cv2


options = {'top': 40, 'left': 0, 'width': 100, 'height': 100} # define dimensions of screen w.r.t to given monitor to be captured

output_params = {"-vcodec":"libx264", "-crf": 0, "-preset": "fast"} #define (Codec,CRF,preset) FFmpeg tweak parameters for writer


stream = ScreenGear(monitor=1, logging=True).start() #Open Live Screencast on current monitor 

writer = WriteGear(output_filename = 'Output.mp4', compression_mode = True, logging = True, **output_params) #Define writer with output filename 'Output.mp4' 

# infinite loop
while True:
	
	frame = stream.read()
	# read frames

	# check if frame is None
	if frame is None:
		#if True break the infinite loop
		break
	

	# {do something with frame here}
        # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

	# write a modified frame to writer
        writer.write(frame) 
       
        # Show output window
	cv2.imshow("Output Frame", frame)

	key = cv2.waitKey(1) & 0xFF
	# check for 'q' key-press
	if key == ord("q"):
		#if 'q' key-pressed break out
		break

cv2.destroyAllWindows()
# close output window

stream.stop()
# safely close video stream
writer.close()
# safely close writer
```

**_In this code which is exactly similar to code you shared but  I removed the `**option` dict from the ScreenGear parameter that defines the portion /area of the computer screen to be captured. Try this code and see the results for yourself. :)_**

**Comment by abhiTronix** [comment] 2019-09-08 03:50
@Seraphli Or you can change the value of `options = {'top': 40, 'left': 0, 'width': 100, 'height': 100}` to something else(for e.g `options = {'top': 100, 'left': 100, 'width': 200, 'height': 200}`) and you will find everything working just as it should be.

**Comment by Seraphli** [comment] 2019-09-08 03:50
Strange. The video is processed by youtube and they fix it. That not the way I saw on my local player. I will upload another video. Wait a second.

**Comment by Seraphli** [comment] 2019-09-08 03:53
Here is the video I saw on my local player. https://youtu.be/qC0f1sN4VB4

**Comment by abhiTronix** [comment] 2019-09-08 03:55
> Here is the video I saw on my local player. https://youtu.be/qC0f1sN4VB4

**Ok that's a problem. On which OS you're running it on?**

**Comment by Seraphli** [comment] 2019-09-08 03:57
Windows 8.1 x64. And I'm using pot player. The decoder information is near the processbar.

**Comment by abhiTronix** [comment] 2019-09-08 03:59
Windows 8.1 x64. And I'm using pot player. The decoder information is near the processbar.

It's not problem with WriteGear/ffmpeg/decoder, basically this is happening because ScreenGear/python-mss API is crashing somewhere due to limited memory.

**Comment by Seraphli** [comment] 2019-09-08 04:01
But I have 16GB memory and it is only used about 65%.

**Comment by abhiTronix** [comment] 2019-09-08 04:07
@Seraphli Wait I'm will try to reproduce results on my Windows 10 x64 machine. I'll get back to you soon.

**Comment by Seraphli** [comment] 2019-09-08 04:07
Okay, thank you!

**Comment by abhiTronix** [comment] 2019-09-08 04:10
@Seraphli It seems working fine here. see this output: 
[Output.zip](https://github.com/abhiTronix/vidgear/files/3587274/Output.zip)

**Comment by Seraphli** [comment] 2019-09-08 04:15
Strange. On my computer the video still has the problem. Let me download another player and try it. BTW, what is the player application you used?

**Comment by abhiTronix** [comment] 2019-09-08 04:15
I use the great mpv video player.

**Comment by abhiTronix** [comment] 2019-09-08 04:20
@Seraphli I just noticed that your output tends to process frames faster than mine, due to more powerful machine of yours. Can you try running about code by adding a little delay (such as `time.sleep(0.1)`) as follows:

```python
# import libraries
from vidgear.gears import ScreenGear
from vidgear.gears import WriteGear
import cv2
import time

options = {'top': 40, 'left': 0, 'width': 100, 'height': 100} # define dimensions of screen w.r.t to given monitor to be captured

output_params = {"-vcodec":"libx264", "-crf": 0, "-preset": "fast"} #define (Codec,CRF,preset) FFmpeg tweak parameters for writer


stream = ScreenGear(monitor=1, logging=True).start() #Open Live Screencast on current monitor 

writer = WriteGear(output_filename = 'Output.mp4', compression_mode = True, logging = True, **output_params) #Define writer with output filename 'Output.mp4' 

# infinite loop
while True:
	
	frame = stream.read()
	# read frames

	# check if frame is None
	if frame is None:
		#if True break the infinite loop
		break
	

	# {do something with frame here}
        # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

	# write a modified frame to writer
        writer.write(frame) 
       
        # Show output window
	cv2.imshow("Output Frame", frame)

	key = cv2.waitKey(1) & 0xFF
	# check for 'q' key-press
	if key == ord("q"):
		#if 'q' key-pressed break out
		break

       # delay of about  0.1 seconds
       time.sleep(0.1)

cv2.destroyAllWindows()
# close output window

stream.stop()
# safely close video stream
writer.close()
# safely close writer
```

**Comment by Seraphli** [comment] 2019-09-08 04:33
I have tried the mpv player. The video works fine in that. So that is a player problem. Seems it can not find the right decoder for the video. The decoder is set to AVC1while playing the video. And what is the right decoder for this video?

**Comment by abhiTronix** [comment] 2019-09-08 04:35
press `i` on `mpv` while playing the video and you can see decoder being used.

**Comment by Seraphli** [comment] 2019-09-08 04:42
![image](https://user-images.githubusercontent.com/1586755/64483534-08d8be80-d236-11e9-8f97-7df0c8e1815c.png)
The decoder for potplayer is also ffmpeg.

**Comment by abhiTronix** [comment] 2019-09-08 04:44
MPV uses OpenGL primarily instead of GPU rendering which makes it more stable.

**Comment by abhiTronix** [comment] 2019-09-08 04:54
@Seraphli Should I consider problem solved?

**Comment by abhiTronix** [comment] 2019-09-08 05:07
**Closing this issue. Feel free to reopen and continue discussion if you experience further problems. Goodluck**

**Closed by abhiTronix** 2019-09-08 05:07 UTC
Labels: question

**Comment by Seraphli** [comment] 2019-09-08 09:09
Consider solved. Just switch to another video player.

**Comment by Seraphli** [comment] 2019-09-08 16:19
Do you notice that after starting `mss`, dragging windows seems laggy?

**Comment by abhiTronix** [comment] 2019-09-08 16:32
Yep, python-mss is too slow on Windows. It's still at the beta stage on Windows which can be seen from its current [issues](https://github.com/BoboTiG/python-mss/issues?q=is%3Aissue+is%3Aopen+label%3AWindows).

**Comment by Seraphli** [comment] 2019-09-08 16:47
Okay. Thanks!

**Comment by Seraphli** [comment] 2019-09-09 03:41
I check the code and find that `monitor` in `ScreenGear` can not be set to 0. mss use index 0 for all monitor. So how to record all monitor in `vidgear`?

**Comment by abhiTronix** [comment] 2019-09-09 03:46
@Seraphli Did you tested that with `python-mss` itself? and Does it works?

**Comment by Seraphli** [comment] 2019-09-09 03:51
Yes, I used mss before using vidgear. It can capture all monitor with index 0. And you can see in the document index 0 stands for all monitors.
![image](https://user-images.githubusercontent.com/1586755/64502338-28d0b680-d2f8-11e9-93ed-50dd8c66fcb8.png)

**Comment by abhiTronix** [comment] 2019-09-09 03:56
> Yes, I used mss before using vidgear. It can capture all monitor with index 0.

@Seraphli Can you share the resultant output? as i don't know, How it handles multiple frames at the same time.

**Comment by Seraphli** [comment] 2019-09-09 03:59
```
import mss

with mss.mss() as sct:
    filename = sct.shot(mon=-1, output='fullscreen.png')
    print(filename)
```
![fullscreen](https://user-images.githubusercontent.com/1586755/64502521-15721b00-d2f9-11e9-9ba6-d8f6b488132f.png)
Screenshot of two monitors is captured .

**Comment by abhiTronix** [comment] 2019-09-09 04:05
> filename = sct.shot(mon=-1, output='fullscreen.png')
@Seraphli Is `mon= -1` and `mon= 0` will give same results here?

**Comment by Seraphli** [comment] 2019-09-09 04:27
`shot` doesn't support `mon=0` for all monitor. But `grab` can use.
```
import mss
import mss.tools


with mss.mss() as sct:
    # Get information of monitor 2
    monitor_number = 0
    mon = sct.monitors[monitor_number]

    output = "sct-mon.png"

    # Grab the data
    sct_img = sct.grab(mon)

    # Save to the picture file
    mss.tools.to_png(sct_img.rgb, sct_img.size, output=output)
    print(output)
```
This code also capturres two monitors.

**Comment by abhiTronix** [comment] 2019-09-09 04:29
@Seraphli Thank you for pointing this out. I've merged a fix to the [**development**](https://github.com/abhiTronix/vidgear/tree/development) branch. **Kindly clone and install this branch as follows:**
```sh
git clone git clone https://github.com/abhiTronix/vidgear.git
cd testing
git checkout development
sudo pip install .
cd
```
Goodluck

**Comment by Seraphli** [comment] 2019-09-09 04:31
Okay. Thanks!
