### ISSUE TITLE
WebGear_RTC: stream freezes after web-page reloading

### ISSUE THREAD

**Issue by kpetrykin** [abhiTronix/vidgear#219] opened 2021-06-08 14:49 UTC
## Description

Hello! Im experimenting with your WebRTC example (https://abhitronix.github.io/vidgear/latest/gears/webgear_rtc/usage/) and everything works fine (stream starts and works even in several browser tabs), but crashes everywhere when I reload page.

To run it again I need to restart whole webserver.

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version: 0.2.1
* Branch: Master, I think
* Python version: 3.8.5
* PiP version: 20.0.2
* Operating System and version: Ubuntu 20.04

### Expected Behavior

Stream continue playing on all tabs with it.

### Actual Behavior

After reloading just one tab with the stream it is being stopped on current tab and freezes on another.

### Possible Fix

Drop connection when page reloads and make new one.

### Steps to reproduce

Run WebRTC example server, connect to it by browser and reload page.

**Comment by abhiTronix** [comment] 2021-06-08 16:41
@kpetrykin Thanks for raising this issue. and Yes it is a known problem in WebGear_RTC that exist since it was created. I tried many methods to cope with it but all fell short. Also it happens rarely that's why I decided to ignore it.

> Drop connection when page reloads and make new one.

It is easy to do on server side in python code. But I can't figure out how to command client browser to drop the connection as well and restart as well. Actually javascripting is not my forte so I might need help there.

**Comment by kpetrykin** [comment] 2021-06-08 18:19
@abhiTronix if you point me to python code, I could play with JS to call it 🤔

**Comment by abhiTronix** [comment] 2021-06-09 05:21
> @abhiTronix if you point me to python code, I could play with JS to call it

@kpetrykin Thanks. First of all,  WebGear_RTC use [`aiortc`](https://github.com/aiortc/aiortc) library at backend for its WebRTC functionality.  Our primary objective will that we need to communicate and tell client that it need to be restarted and receive a feedback so that server can restart too afterwards. We can do something like this example: https://github.com/aiortc/aiortc/tree/main/examples/server (more details of its working can be found on its readme). Also take a look at https://github.com/aiortc/aiortc/tree/main/examples/webcam, I took ideas from these examples while creating  WebGear_RTC API.

Here is the offer that WebGear_RTC create to talk with client(s):
https://github.com/abhiTronix/vidgear/blob/eb19b9ce96061c09b5fe4c3ee63d84c940a19af2/vidgear/gears/asyncio/webgear_rtc.py#L452-L509

And here is the [js](https://github.com/abhiTronix/vidgear-vitals/blob/main/webgear_rtc/static/js/custom.js) file that WebGear_RTC uses and we need to communicate with.

**Comment by kpetrykin** [comment] 2021-06-10 10:27
I made brutal example, which closes all connections and relaunches videostream on page reloading (JS sends request to special endpoint) - and now there is no freezes.
But it breaks the stream on another tabs =\

**Comment by abhiTronix** [comment] 2021-06-10 11:06
> I made brutal example, which closes all connections and relaunches videostream on page reloading (JS sends request to special endpoint) - and now there is no freezes.
But it breaks the stream on another tabs =\

@kpetrykin That's awesome start and I might able to help with it. Can I take a look at it? 😃

**Comment by kpetrykin** [comment] 2021-06-10 13:35
I made PR: https://github.com/abhiTronix/vidgear/pull/221

**Comment by abhiTronix** [comment] 2021-06-10 14:04
> I made PR: #221

@kpetrykin Please resolve: https://github.com/abhiTronix/vidgear/pull/221#issuecomment-858649458

**Comment by abhiTronix** [comment] 2021-06-12 17:53
@kpetrykin Finally I've solved this problem with your suggestions, so thanks to you 😃. You're on right track but it needed some major changes to API. Please hold on for the commit, I'll notify you here.

**Comment by abhiTronix** [comment] 2021-06-15 02:03
@kpetrykin The issue is resolved in latest commit https://github.com/abhiTronix/vidgear/commit/4de88c77dc3ce9109f2ae85240b0440ff715d7d0. Kindly  test it on your setup by installing `development` branch as follows:
```sh
 # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest development branch
  git checkout development

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```

After installing use following code to re-generated JS an HTML files:

```python
# import required libraries
import uvicorn
from vidgear.gears.asyncio import WebGear_RTC

# various performance tweaks
options = {
    "frame_size_reduction": 30,
    "overwrite_default_files": True,
}

# initialise WebGear_RTC app with proper source
web = WebGear_RTC(
    source="video.mp4", logging=True, **options
)

# run this app on Uvicorn server at address http://localhost:8000/
uvicorn.run(web(), host="localhost", port=8000)

# close app safely
web.shutdown()
```
and you'll be able to reload page any number of times without freezing. 😃 

**Kindly test it as soon as possible and share your results here**. Goodluck!

**Comment by abhiTronix** [comment] 2021-06-22 06:07
**Marked solved, as working as intended. Feel free to test it and provide valuable feedback when possible.**

**Closed by abhiTronix** 2021-06-22 06:07 UTC
Labels: :beetle: BUG, IN PROGRESS :construction:, WAITING FOR RESPONSE :hourglass_flowing_sand:, WAITING TO TEST :timer_clock:

**Comment by abhiTronix** [comment] 2021-06-22 06:08
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/2076d8c47e4c1383f57aecac362ea28bc95aaaea**

**Comment by kpetrykin** [comment] 2021-06-22 12:54
Sorry, I can't test it soon, because I start to work on another project.
But I mandatory test it in the future!
