### ISSUE TITLE
PiGear :: ERROR :: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by GhaythHilal** [abhiTronix/vidgear#119] opened 2020-03-15 17:02 UTC
## Description
I was trying to run the [example](https://github.com/abhiTronix/vidgear/wiki/PiGear) provided for the usage of the PiGear module
### Environment

* VidGear version: 0.1.6
* Branch: PyPi
* Python version: 3
* pip version: 3
* Operating System and version: Raspbian GNU/Linux 10 (Buster)

### Expected Behavior
Show camera stream

### Actual Behavior
I'm receiving the following error:

PiGear :: DEBUG :: Activating Pi camera at index: 0 with resolution: (320, 240) & framerate: 60
PiGear :: ERROR :: an integer is required (got type NoneType)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/vidgear/gears/pigear.py", line 147, in __init__
    if not(self.frame is None and self.color_space is None): self.frame = cv2.cvtColor(self.frame, self.color_space)
TypeError: an integer is required (got type NoneType)

### Steps to reproduce
copy the sample code form the PiGear API page and run it as is

### Note
if I use the CamGear module instead (like the code snippet below) I get no errors: 

`from vidgear.gears import CamGear`
`import cv2`

`stream = cv2.VideoCapture(0)`

`while True:`
`(grabbed, frame) = stream.read()`
`    if frame is None:`
`        break`
`    cv2.imshow("Output Frame", frame)`

**Comment by abhiTronix** [comment] 2020-03-16 01:27
@GhaythHilal Duplicate of #113. This bug is already fixed in commit e421975 and related PR is #114. **Kindly install latest testing branch with instructions given below:**
```sh
git clone git clone https://github.com/abhiTronix/vidgear.git
cd vidgear
git checkout testing
sudo pip install .
cd
````

**Closed by abhiTronix** 2020-03-16 01:27 UTC
Labels: Bug :beetle:, Duplicate :recycle:
